In [1]:
k=[4,2.56789,9,87.9999,40,'hyderabad']
k

[4, 2.56789, 9, 87.9999, 40, 'hyderabad']

In [3]:
import pandas as pd
import numpy as np
import seaborn as sns

In [8]:
k=[4,2.56789,9,87.9999,40]
k

[4, 2.56789, 9, 87.9999, 40]

In [9]:
pd.Series(k)

0     4.00000
1     2.56789
2     9.00000
3    87.99990
4    40.00000
dtype: float64

In [12]:
a=np.random.randint(20,50,15)
a

array([47, 41, 20, 47, 42, 47, 20, 49, 28, 45, 41, 41, 21, 30, 31])

In [13]:
a.ndim

1

In [15]:
s=pd.Series(a)
s

0     47
1     41
2     20
3     47
4     42
5     47
6     20
7     49
8     28
9     45
10    41
11    41
12    21
13    30
14    31
dtype: int64

In [16]:
s[0]

47

In [18]:
s[4:10]

4    42
5    47
6    20
7    49
8    28
9    45
dtype: int64

In [20]:
b=np.random.randint(100,200,(6,5))
b

array([[171, 109, 175, 184, 182],
       [155, 198, 104, 128, 120],
       [184, 134, 194, 130, 124],
       [142, 163, 121, 129, 174],
       [154, 114, 133, 143, 135],
       [180, 170, 150, 129, 128]])

In [21]:
b.ndim

2

In [22]:
b.shape

(6, 5)

In [31]:
df=pd.DataFrame(b,columns=['Roll','name','age','country','adds'],index=[182,183,185,186,187,188]
df

SyntaxError: '(' was never closed (<ipython-input-31-6e2a797da357>, line 1)

In [32]:
df

   Roll  name  age  Country  Adress
0   171   109  175      184     182
1   155   198  104      128     120
2   184   134  194      130     124
3   142   163  121      129     174
4   154   114  133      143     135
5   180   170  150      129     128

In [36]:
df.iloc[0,0]

171

In [37]:
df.loc[182,'Roll']

KeyError: 182

In [38]:
df.iloc[0,0:3]

Roll    171
name    109
age     175
Name: 0, dtype: int64

In [39]:
df.iloc[[0,5]]

   Roll  name  age  Country  Adress
0   171   109  175      184     182
5   180   170  150      129     128

In [40]:
df.iloc[[1,3,4]]

   Roll  name  age  Country  Adress
1   155   198  104      128     120
3   142   163  121      129     174
4   154   114  133      143     135

In [41]:
df

   Roll  name  age  Country  Adress
0   171   109  175      184     182
1   155   198  104      128     120
2   184   134  194      130     124
3   142   163  121      129     174
4   154   114  133      143     135
5   180   170  150      129     128

In [42]:
df.age

0    175
1    104
2    194
3    121
4    133
5    150
Name: age, dtype: int64

In [43]:
df['age']

0    175
1    104
2    194
3    121
4    133
5    150
Name: age, dtype: int64

In [44]:
df[['age','adds']]

KeyError: "['adds'] not in index"

In [45]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [48]:
sns.load_dataset('planets')

               method  number  orbital_period   mass  distance  year
0     Radial Velocity       1      269.300000   7.10     77.40  2006
1     Radial Velocity       1      874.774000   2.21     56.95  2008
2     Radial Velocity       1      763.000000   2.60     19.84  2011
3     Radial Velocity       1      326.030000  19.40    110.62  2007
4     Radial Velocity       1      516.220000  10.50    119.47  2009
...               ...     ...             ...    ...       ...   ...
1030          Transit       1        3.941507    NaN    172.00  2006
1031          Transit       1        2.615864    NaN    148.00  2007
1032          Transit       1        3.191524    NaN    174.00  2007
1033          Transit       1        4.125083    NaN    293.00  2008
1034          Transit       1        4.187757    NaN    260.00  2008

[1035 rows x 6 columns]

In [49]:
type(df)

pandas.core.frame.DataFrame

In [50]:
df.shape

(6, 5)

In [51]:
df.columns

Index(['Roll', 'name', 'age', 'Country', 'Adress'], dtype='object')